### ISSUE TITLE
Provide Versions

### ISSUE THREAD

**Issue by shortstuffsushi** [brianc/node-deprecate#1]
Hey, just a suggestion that would make it clearer for developers, maybe add the ability to provide an "as of x.x.x" option, and possible also an "available until y.y.y" as well.

Not sure what the cleanest API for doing this would be, but as someone who is getting these messages, it's often useful to see when the method changed to understand why it's being changed.

Currently both methods in your API are unused (methodName, message), and you instead log all arguments. A list of messages doesn't really seem necessary though, couldn't it just be something like `function deprecate(methodName, message, asOfVersion, untilVersion)`?

Then you could log something like

```
WARNING!!
(As of x.x.x) someDeprecatedFunction() is deprecated (will be removed in y.y.y)
```

Just an idea, it could just as easily be pushed onto the dev calling `deprecate`, but it seems like this would be a convenience.

**Comment by punmechanic** [comment]
I think adding a "as of x.x.x" idea could good, however, "until y.y.y" doesn't make sense if the owner is adhering to semver (which they should be); semver dictates you can only remove public-facing APIs un major version upgrades, and so there's no need for an "until".

Given that, I think it's a relatively small change and I think as a result it should be done by the end-user rather than the library.

**Comment by shortstuffsushi** [comment]
In general, I agree about using semver, though I don't think you can rely on that being the case. Reading through my own proposal, I'd rather drop the `until`, but I still think standardizing the `asOf` would be useful (rather than having every developer implement that themselves). As noted, you could just as easily push that on the dev, but then obviously their aren't going to be as many people taking advantage of it. Up to you guys, though.

**Comment by punmechanic** [comment]
>  though I don't think you can rely on that being the case
> As noted, you could just as easily push that on the dev, but then obviously their aren't going to be as many people taking advantage of it. 

You should push it on the dev instead of enforcing your view on them in that case. In any case, every package in npm uses semver, so you might as well agree its a standard. The exception being underscore, who rather tongue-in-cheek **refused** to use it

**Comment by shortstuffsushi** [comment]
I'd rather not argue about it, but I disagree with both of your points. It's not my library, nor one I'm using, so it's not really critical to me, it was just something I thought could be useful.
