### ISSUE TITLE
Crashes in browser

### ISSUE THREAD

**Issue by j-maas** [brianc/node-deprecate#5]
Deprecate will crash when imported in a browser. I know this is not where it's mainly intended to run, but I think that it has a somewhat easy fix.

In a [Nestjs] server I'm writing, I want to expose the model to other modules. Because of poor reflection abilities, I have to decorate each of the model's classes' properties with [`@ApiModelProperty()`](https://docs.nestjs.com/recipes/swagger). That decorator uses `deprecate`.

This runs all fine on Node.js. But I use the model inside the browser client, where the app won't even load. It ultimately crashes [on `deprecate.stream.isTTY`](https://github.com/brianc/node-deprecate/blob/master/index.js#L28), because `deprecate.stream` is not defined, since `process.stderr` doesn't exist in the browser. (I don't know how to easily reproduce this, sorry.)

Is it possible to guard this with feature detection? Or is this something that has to be handled in the usage of this library, not the library itself?

[Nestjs]: https://nestjs.com/

**Comment by conartist6** [comment]
I'll fix this. Feature detection consists of seeing if the process global exists.

**Comment by conartist6** [comment]
I lied, this is probably a wontfix. Pretty much all the functionality of this library does not work in a browser. Color doesn't work. Choosing streams doesn't work. Most importantly, this library is meant to only warn once per usage of a deprecated function, but that functionality is based on [function.caller](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/caller).

**Comment by conartist6** [comment]
What's worse it's based on stringifying `function.caller`, which is as dubious a strategy as I can imagine.

**Comment by conartist6** [comment]
I lied again, I fixed it.

**Comment by j-maas** [comment]
What a rollercoaster ride. :D Thank you!
